close all;
figure;

sgd = subplot(2,3,1)

plot(iteration_SGD_l1_64, f1_score_SGD_l1_64,'b*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(iteration_SGD_l1_128, f1_score_SGD_l1_128, 'g*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[1,1,1])
hold on
pbaspect(sgd, [1 1 1])
xlim([160,500])
ylim([0.5, 0.7])
set(gca,'FontSize', 25);
hold off
%Label & Legend for PingAvg
t = title('SGD Classifier L1')
t.FontSize = 22
xlabel('Number of Iteration', 'FontSize', 25)
ylabel('F1-Score]', 'FontSize', 25)
l = legend('64 x 64', '128 x 128', 'Location', 'northoutside', 'Orientation','horizontal');
l.FontSize = 22
grid on


randFor = subplot(2,3,2)

plot(n_estimator_RF_64, f1_score_RF_64, 'b*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_RF_128, f1_score_RF_128, 'g*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[1,1,1])
hold on
xlim([500, 3000])
ylim([0.5, 0.7])
pbaspect(randFor, [1 1 1])
set(gca,'FontSize', 25);
hold off
%Label & Legend for PingAvg
t = title('Random Forest')
t.FontSize = 22
xlabel('Number of Estimator', 'FontSize', 25)
ylabel('F1-Score]', 'FontSize', 25)
l = legend('64 x 64', '128 x 128', 'Location', 'northoutside', 'Orientation','horizontal');
l.FontSize = 22
grid on

KNN = subplot(2,3,3)

plot(n_estimator_KNN_64, f1_score_KNN_uniform_64, 'b*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_KNN_128, f1_score_KNN_uniform_128, 'g*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_KNN_64, f1_score_KNN_distance_64, 'c*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','c',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_KNN_128, f1_score_KNN_distance_128, 'm*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','m',...
    'MarkerFaceColor',[1,1,1])
hold on
xlim([3, 9])
%ylim([0.2, 0.7])
pbaspect(KNN, [1 1 1])
set(gca,'FontSize', 25);
hold off
%Label & Legend for PingAvg
t = title('K-Nearest Neighbor')
t.FontSize = 22
xlabel('Number of Neighbors', 'FontSize', 25)
ylabel('F1-Score]', 'FontSize', 25)
l = legend('Uniform  | 64 x 64', 'Uniform  | 128 x 128', 'Distance | 64 x 64', 'Distance | 128 x 128',  'Location', 'northoutside', 'Orientation','vertical');
l.FontSize = 22
grid on


adaBoost = subplot(2,3,4)

plot(n_estimator_ADA_64_1, f1_score_ADA_64_1, 'b*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_128_1, f1_score_ADA_128_1, 'g*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_64_2, f1_score_ADA_64_2, 'c*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','c',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_128_2, f1_score_ADA_128_2, 'm*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','m',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_64_3, f1_score_ADA_64_3, 'r*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_128_3, f1_score_ADA_128_3, 'k*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor',[1,1,1])
hold on

%xlim([3, 9])
%ylim([0.2, 0.7])
pbaspect(adaBoost, [1 1 1])
set(gca, 'FontSize', 25);
hold off
%Label & Legend for PingAvg
t=title('AdaBoost')
t.FontSize = 22
xlabel('Number of Estimators', 'FontSize', 25)
ylabel('F1-Score]', 'FontSize', 25)
l = legend('Learning Rate = 0.05 | 64x64', 'Learning Rate = 0.05 | 128x128', 'Learning Rate = 0.1   | 64x64', 'Learning Rate = 0.1   | 128x128', 'Learning Rate = 0.15 | 64x64','Learning Rate = 0.15 | 128x128', 'Location', 'northoutside', 'Orientation','vertical');
l.FontSize = 22
grid on


%%%%%%%%%%%%%%%%%%%%%%%%%%

sgd_comp = subplot(2,3,5)

plot(l1_SGD_64_n, l1_SGD_64_F1, 'b*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(l1_SGD_128_n, l1_SGD_128_F1, 'g*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(l1_SGD_64_n, l2_SGD_64_F1, 'c*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','c',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(l1_SGD_64_n, l2_SGD_128_F1, 'm*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','m',...
    'MarkerFaceColor',[1,1,1])
hold on
xlim([160, 240])
ylim([0.4, 0.6])
pbaspect(sgd_comp, [1 1 1])
set(gca,'FontSize', 25);
hold off
%Label & Legend for PingAvg
t = title('SGD Classifier')
t.FontSize = 22
xlabel('Number of Iteration', 'FontSize', 25)
ylabel('F1-Score]', 'FontSize', 25)
l = legend('Penalty = L1 | 64x64', 'Penalty = L1 | 128x128', 'Penalty = L2 | 64x64', 'Penalty = L2 | 128x128',  'Location', 'northoutside', 'Orientation','vertical');
l.FontSize = 22
grid on