adaBoost = subplot(1,1,1)

plot(n_estimator_ADA_64_1, f1_score_ADA_64_1, 'b*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_128_1, f1_score_ADA_128_1, 'g*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_64_2, f1_score_ADA_64_2, 'c*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','c',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_128_2, f1_score_ADA_128_2, 'm*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','m',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_64_3, f1_score_ADA_64_3, 'r*-',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor',[1,1,1])
hold on
plot(n_estimator_ADA_128_3, f1_score_ADA_128_3, 'k*--',...
    'LineWidth',2,...
    'MarkerSize',4,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor',[1,1,1])
hold on

%xlim([3, 9])
%ylim([0.2, 0.7])
pbaspect(adaBoost, [1 1 1])
set(gca, 'FontSize', 25);
hold off
%Label & Legend for PingAvg
t=title('AdaBoost')
t.FontSize = 22
xlabel('Number of Estimators', 'FontSize', 25)
ylabel('F1-Score]', 'FontSize', 25)
l = legend('Learning Rate = 0.05 | 64x64', 'Learning Rate = 0.05 | 128x128', 'Learning Rate = 0.1   | 64x64', 'Learning Rate = 0.1   | 128x128', 'Learning Rate = 0.15 | 64x64','Learning Rate = 0.15 | 128x128', 'Location', 'northoutside', 'Orientation','vertical');
l.FontSize = 22
grid on
